=== aldl1910/ExUD4LMSGI/ExUD4/Ex_UD4.dtd
<!ELEMENT sucursal (exposicion|gestion)*>
<!ELEMENT exposicion (pedido|articulos)*>
<!ELEMENT pedido (datos|direcciones|codigo|NomTra|fecha|Obs)*>
<!ELEMENT datos (#PCDATA)>
<!ELEMENT direcciones (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ATTLIST codigo codSuc CDATA #REQUIRED>
<!ELEMENT NomTra (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT Obs (#PCDATA)>
<!ELEMENT articulos (cod|UniPed|Precio|Obse|Plazo)*>
<!ATTLIST cod codArt CDATA #REQUIRED>
<!ELEMENT cod (#PCDATA)>
<!ELEMENT UniPed (#PCDATA)>
<!ELEMENT Precio (#PCDATA)>
<!ELEMENT Obse (#PCDATA)>
<!ELEMENT Plazo (#PCDATA)>
<!ELEMENT gestion (albaran|pago)*>
<!ELEMENT albaran (#PCDATA)>
<!ELEMENT pago (#PCDATA)>

=== aldl1910/ExUD4LMSGI/ExUD4/Ex_UD4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sucursal SYSTEM "Ex_UD4.dtd">
<sucursal>
    <exposicion>
        <pedido>
            <datos></datos>
            <direcciones>Calle del Perd√≥n</direcciones>
            <codigo codSuc="A_______"></codigo>
            <NomTra>Rosa Perez</NomTra>
            <fecha>2001/10/19</fecha>
            <Obs></Obs>
        </pedido>
        <articulos>
            <cod codArt="AAA-777"></cod>
            <UniPed></UniPed>
            <Precio></Precio>
            <Obse ></Obse>
            <Plazo></Plazo>
        </articulos>
    </exposicion>
    <gestion>
        <albaran></albaran>
        <pago></pago>
    </gestion>
</sucursal>
